package GUI;

import com.digitalpersona.onetouch.DPFPGlobal;
import com.digitalpersona.onetouch.capture.DPFPCapture;
import com.digitalpersona.onetouch.capture.event.DPFPDataAdapter;
import com.digitalpersona.onetouch.capture.event.DPFPDataEvent;
import com.digitalpersona.onetouch.capture.event.DPFPReaderStatusAdapter;
import com.digitalpersona.onetouch.capture.event.DPFPReaderStatusEvent;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import logica.HiloVerificarHuella;

/**
 *@author Maria Alejandra Martos Diaz
 * @author Mateo Cano Alfonso
 * @author Juan Jefferson Alape
 */
public class VentanaIngresoEstudiante extends JFrame {
    //para poder hacer el ingreso

    HiloVerificarHuella hiloVerificarHuella;

    public static VentanaIngresoEstudiante ventana;
    Connection cn;
    PreparedStatement pst;
    ResultSet rst;

    /**
     * Creates new form LogInEstudiante
     */
    public VentanaIngresoEstudiante() {

        start();
        Iniciar();
        initComponents();
        this.getContentPane().setBackground(Color.white);
         hiloVerificarHuella= new HiloVerificarHuella(jLabelImagenHuella);

    }

    /**
     * Patron Singleton
     *
     * @return
     */
    public static VentanaIngresoEstudiante getInstaceSingleton() {
        if (ventana == null) {
            ventana = new VentanaIngresoEstudiante();
        }
        return ventana;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new JLabel();
        jLabelContenido = new JLabel();
        jLabelContenido2 = new JLabel();
        jPanelHuella = new JPanel();
        jPanelContenedorHuella = new JPanel();
        jLabelImagenHuella = new JLabel();
        jButtonInicioSesionDoc = new JButton();
        jButtonAtras = new JButton();
        jLabelConexionHuellero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Ingreso del Estudiante");
        setIconImage(getIconImage());
        setName("VentanaInicioSesionEstudiante"); // NOI18N
        setResizable(false);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitulo.setText("Registrar Ingreso del Estudiante");

        jLabelContenido.setBackground(new java.awt.Color(255, 255, 255));
        jLabelContenido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelContenido.setText("<html>Si desea registrar el ingreso con la huella dactilar, favor colocar <br> el dedo índice en el lector de huellas.</html>");

        jLabelContenido2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelContenido2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelContenido2.setText("<html>Si desea registrar el ingreso con el documento de identidad del estudiante hacer clic en el botón Registrar Ingreso por Documento.</html>");

        jPanelHuella.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHuella.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Huella Dactilar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jPanelContenedorHuella.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelContenedorHuellaLayout = new javax.swing.GroupLayout(jPanelContenedorHuella);
        jPanelContenedorHuella.setLayout(jPanelContenedorHuellaLayout);
        jPanelContenedorHuellaLayout.setHorizontalGroup(
            jPanelContenedorHuellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorHuellaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImagenHuella, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelContenedorHuellaLayout.setVerticalGroup(
            jPanelContenedorHuellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorHuellaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImagenHuella, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelHuellaLayout = new javax.swing.GroupLayout(jPanelHuella);
        jPanelHuella.setLayout(jPanelHuellaLayout);
        jPanelHuellaLayout.setHorizontalGroup(
            jPanelHuellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedorHuella, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelHuellaLayout.setVerticalGroup(
            jPanelHuellaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedorHuella, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButtonInicioSesionDoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonInicioSesionDoc.setText("Registro Ingreso Por Documento");
        jButtonInicioSesionDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioSesionDocActionPerformed(evt);
            }
        });

        jButtonAtras.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonAtras.setText("Atras");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        jLabelConexionHuellero.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelHuella, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonInicioSesionDoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAtras))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelContenido2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabelTitulo))
                            .addComponent(jLabelConexionHuellero, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jLabelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelContenido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelConexionHuellero, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelHuella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInicioSesionDoc)
                    .addComponent(jButtonAtras))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param evt
     */
    private void jButtonInicioSesionDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioSesionDocActionPerformed
        stop();
        VentanaInciarSesionDocumento.getInstaceSingleton().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonInicioSesionDocActionPerformed

    /**
     *
     * @param evt
     */
    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        stop();
        VentanaPrincipal.getInstaceSingleton().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonAtrasActionPerformed

    /**
     *
     * @return
     */
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/Escudo.png"));

        return retValue;
    }
    // Varible que permite iniciar el dispositivo de lector de huella conectado
    // con sus distintos metodos.
    private final DPFPCapture Lector = DPFPGlobal.getCaptureFactory().createCapture();

    /**
     * Metodo que sirve para iniciar el lector de huellas
     */
    protected final void Iniciar() {

        Lector.addDataListener(dataAdapter);

        Lector.addReaderStatusListener(new DPFPReaderStatusAdapter() {
            @Override
            public void readerConnected(final DPFPReaderStatusEvent e) {
                jLabelConexionHuellero.setForeground(Color.GREEN);
                jLabelConexionHuellero.setText("El Sensor de Huella Digital esta Conectado");
            }

            @Override
            public void readerDisconnected(final DPFPReaderStatusEvent e) {
                jLabelConexionHuellero.setForeground(Color.RED);
                jLabelConexionHuellero.setText("El Sensor de Huella Digital No esta Conectado");
            }
        });

    }

    /**
    * Método que indica que el lector de huella se va a empezar a utilizar
     */
    public final void start() {
        Lector.startCapture();
    }

    /**
     * Metodo que indica que el lector de huella no esta en uso
     */
    public void stop() {
        Lector.stopCapture();
    }

    /**
     * Variable que permite inicar el hilo para procesar las huellas
     */
    DPFPDataAdapter dataAdapter = new DPFPDataAdapter() {
        @Override
        public void dataAcquired(final DPFPDataEvent e) {
            hiloVerificarHuella.setSample(e.getSample());
            SwingUtilities.invokeLater(hiloVerificarHuella);
        }

    };
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonInicioSesionDoc;
    private javax.swing.JLabel jLabelConexionHuellero;
    private javax.swing.JLabel jLabelContenido;
    private javax.swing.JLabel jLabelContenido2;
    private javax.swing.JLabel jLabelImagenHuella;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelContenedorHuella;
    private javax.swing.JPanel jPanelHuella;
    // End of variables declaration//GEN-END:variables

    
  

}
